skills_keywords:
  - python
  - sql
  - data analysis
  - visualization
  - tableau
  - power bi
  - excel
  - machine learning
  - statistics
  - r
  - sas
  - spss
  - data mining
  - big data
  - hadoop
  - spark
  - aws
  - azure
  - google cloud
  - data warehouse
  - etl
  - bi
  - business intelligence
  - data science
  - predictive modeling
  - data governance
  - data quality
  - data cleansing
  - data integration
  - data visualization
  - dashboard
  - reporting
  - kpi
  - metrics
  - analytics